// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNvcwxgimeZ5aOYLgf3yREaPZOW_i9wpk',
    appId: '1:843181823200:android:5ad57bb1f0ee7e18b02c85',
    messagingSenderId: '843181823200',
    projectId: 'languagerally',
    storageBucket: 'languagerally.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBFncg2LZTCabVFd8i2F7WTYk0Dgmj9rc',
    appId: '1:843181823200:ios:1d51453f129ef6fdb02c85',
    messagingSenderId: '843181823200',
    projectId: 'languagerally',
    storageBucket: 'languagerally.firebasestorage.app',
    iosBundleId: 'com.github.pittnerf.languagerally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBFncg2LZTCabVFd8i2F7WTYk0Dgmj9rc',
    appId: '1:843181823200:ios:39d1040a0704f9e9b02c85',
    messagingSenderId: '843181823200',
    projectId: 'languagerally',
    storageBucket: 'languagerally.firebasestorage.app',
    iosBundleId: 'com.example.languageRally',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCO9hs1eeXHVCFqyT1C-prnqFXV9bH4VtU',
    appId: '1:843181823200:web:e6d5bfa720bf9e81b02c85',
    messagingSenderId: '843181823200',
    projectId: 'languagerally',
    authDomain: 'languagerally.firebaseapp.com',
    storageBucket: 'languagerally.firebasestorage.app',
    measurementId: 'G-GH0VJ3MB23',
  );
}
